# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/server'
    directory: '/'
    # Check for updates
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/client'
    # Check for updates
    schedule:
      interval: 'monthly'
      interval: 'daily'
    # Dependencies to ignore
    ignore:
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: '@types/react-dom'
      - dependency-name: '@types/react'
    # Maximum allowed open pull requests
    open-pull-requests-limit: 10