version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates
    schedule:
      interval: "daily"
    # Dependencies to ignore
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "@types/react-dom"
      - dependency-name: "@types/react"
    # Maximum allowed open pull requests
    open-pull-requests-limit: 10
